# Generated by Django 3.1 on 2020-09-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=8)),
                ('site_name', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
                ('cause_of_loss', models.CharField(max_length=100)),
                ('case_category', models.CharField(max_length=20)),
                ('case_date', models.DateField()),
                ('insurance_register', models.CharField(max_length=50)),
                ('create_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
