# Generated by Django 3.1 on 2020-09-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stolen_forcemajeure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='case_category',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='case_date',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='cause_of_loss',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='insurance_register',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='vendor',
        ),
    ]
