# Generated by Django 3.1 on 2020-10-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stolen_forcemajeure', '0002_auto_20200916_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='sites',
            name='micro_cluster',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='ne_state',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='area',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='region',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='site_name',
            field=models.CharField(max_length=100),
        ),
    ]
