# Generated by Django 3.1 on 2020-10-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stolen_forcemajeure', '0003_auto_20201020_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='ne_state',
            field=models.CharField(max_length=6),
        ),
    ]
