# Generated by Django 3.1 on 2020-09-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart_mgt', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tb_sfm_sites',
        ),
    ]
